Repository pingcap/tidb-dashboard, pull requests merged in 2020-03, with the labels that each got.

#143 keyvisual: control start and stop
  cmd/tidb-dashboard/main.go
  pkg/keyvisual/service.go
Labels: area/foundation

#183 Add parrallel in compare table and add max_diff_ratio table.
  pkg/apiserver/diagnose/compare.go
  pkg/apiserver/diagnose/report.go
  pkg/apiserver/diagnose/report_test.go
Labels: area/diagnosis

#189 diagnose: fix cpu usage bug and refine report format
  pkg/apiserver/diagnose/compare.go
  pkg/apiserver/diagnose/query.go
  pkg/apiserver/diagnose/report.go
Labels: area/diagnosis

#198 diagnose: refine compare diff table and add process memory usage.
  pkg/apiserver/diagnose/compare.go
  pkg/apiserver/diagnose/query.go
  pkg/apiserver/diagnose/report.go
  pkg/apiserver/diagnose/report_test.go
Labels: area/diagnosis

#201 diagnose: fix tikv thread cpu report and add sort for some table.
  pkg/apiserver/diagnose/compare.go
  pkg/apiserver/diagnose/inspection.go
  pkg/apiserver/diagnose/query.go
  pkg/apiserver/diagnose/report.go
  pkg/apiserver/diagnose/report_test.go
Labels: area/diagnosis

#285 *: fix duplicate handler bug
  pkg/apiserver/apiserver.go
Labels: type/bug

#291 add device label for node disk latency
  pkg/apiserver/diagnose/query.go
  pkg/apiserver/diagnose/report.go
  pkg/apiserver/diagnose/report_test.go
Labels: area/backend
