Repository pingcap/tidb-dashboard, pull requests merged in 2020-12, with the labels that each got.

#823 fix duplicated y-axis label
  ui/lib/components/MetricChart/index.tsx
Labels: status/LGT1

#811 Upgrade antd
  ui/lib/apps/ClusterInfo/pages/List.module.less
  ui/lib/apps/ClusterInfo/pages/List.tsx
  ui/lib/apps/SlowQuery/pages/Detail/index.tsx
  ui/lib/apps/Statement/pages/Detail/PlanDetail.tsx
  ui/lib/components/CardTabs/index.module.less
  ui/lib/components/CardTabs/index.tsx
  ui/package.json
  ui/yarn.lock
Labels: status/LGT1, status/can-merge

#814 Upgrade ahooks
  ui/dashboardApp/layout/main/Sider/Banner.tsx
  ui/dashboardApp/layout/main/Sider/index.tsx
  ui/dashboardApp/layout/main/index.tsx
  ui/dashboardApp/layout/signin/index.tsx
  ui/lib/apps/ClusterInfo/components/InstanceTable.tsx
  ui/lib/apps/Configuration/InlineEditor.tsx
  ui/lib/apps/Configuration/index.tsx
  ui/lib/apps/InstanceProfiling/pages/Detail.tsx
  ui/lib/apps/InstanceProfiling/pages/List.tsx
  ui/lib/apps/KeyViz/components/KeyViz.tsx
  ui/lib/apps/KeyViz/heatmap/index.tsx
  ui/lib/apps/QueryEditor/Editor.tsx
  ui/lib/apps/SearchLogs/components/SearchHeader.tsx
  ui/lib/apps/SlowQuery/components/SlowQueriesTable.tsx
  ui/lib/apps/SlowQuery/pages/Detail/index.tsx
  ui/lib/apps/SlowQuery/pages/List/index.tsx
  ui/lib/apps/SlowQuery/utils/useSlowQueryTableController.ts
  ui/lib/apps/Statement/components/StatementsTable.tsx
  ui/lib/apps/Statement/pages/Detail/PlanDetail.tsx
  ui/lib/apps/Statement/pages/Detail/index.tsx
  ui/lib/apps/Statement/pages/List/index.tsx
  ui/lib/apps/Statement/utils/useStatementTableController.ts
  ui/lib/apps/SystemReport/components/ReportHistory.tsx
  ui/lib/components/AppearAnimate/index.tsx
  ui/lib/components/BaseSelect/index.tsx
  ui/lib/components/CardTable/GroupHeader.tsx
  ui/lib/components/CardTable/index.tsx
  ui/lib/components/InstanceSelect/TableWithFilter.tsx
  ui/lib/components/InstanceSelect/index.tsx
  ui/lib/components/MultiSelect/index.tsx
  ui/lib/utils/useClientRequest.ts
  ui/lib/utils/useOrderState.ts
  ui/package.json
  ui/yarn.lock
Labels: status/LGT1, status/can-merge

#827 fix issue of query topn statement get error
  pkg/apiserver/statement/queries.go
Labels: status/LGT1, status/can-merge, type/bug

#830 show indents for slow query detail time more elegantly
  ui/lib/apps/SlowQuery/pages/Detail/DetailTabTime.tsx
  ui/lib/apps/SlowQuery/translations/en.yaml
  ui/lib/apps/SlowQuery/translations/zh.yaml
  ui/lib/utils/tableColumns.tsx
Labels: status/LGT1
