Repository pingcap/tidb-dashboard, pull requests merged in 2023-09, with the labels that each got.

#1585 chore: update swaggo
  go.mod
  go.sum
  scripts/go.mod
  scripts/go.sum
Labels: lgtm, approved, size/L

#1587 test(login): fix login integration test
  pkg/apiserver/user/auth.go
  pkg/apiserver/user/rsa_utils.go
  pkg/apiserver/user/sqlauth/sqlauth.go
  tests/integration/info/info_test.go
  tests/integration/user/user_test.go
Labels: lgtm, approved, size/M

#1590 chore: hide resource manager and overview monitoring for clinic cloud
  ui/packages/tidb-dashboard-for-clinic-cloud/public/index.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Overview/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Metrics.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Overview/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/Overview/index.tsx
Labels: area/frontend, size/M

#1591 Update OWNERS
  OWNERS
Labels: lgtm, approved, size/S

#1592 security fixes
  pkg/apiserver/conprof/service.go
  pkg/apiserver/resource_manager/service.go
  pkg/apiserver/statement/queries.go
Labels: lgtm, approved, size/S

#1593 hide full stacktrace info in error message
  util/rest/context_helpers.go
  util/rest/error_resp.go
Labels: lgtm, approved, size/S

#1596 Release v2023.09.21.01 [skip pd_pr]
  pkg/apiserver/conprof/service.go
  pkg/apiserver/resource_manager/service.go
  pkg/apiserver/statement/queries.go
  release-version
  util/rest/context_helpers.go
  util/rest/error_resp.go
Labels: lgtm, approved, size/S

#1597 release 6.5 security fix
  pkg/apiserver/conprof/service.go
  pkg/apiserver/resource_manager/service.go
  pkg/apiserver/statement/queries.go
  util/rest/context_helpers.go
  util/rest/error_resp.go
Labels: size/S

#1598 feat(statements): show `plan_cache_hits` field
  pkg/apiserver/statement/models.go
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetailTabBasic.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/tableColumns.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
Labels: area/frontend, lgtm, approved, size/S
