Repository pingcap/tidb-dashboard, pull requests merged in 2023-10, with the labels that each got.

#1450 tweak: make the goroutine profile more verbose
  pkg/apiserver/profiling/pprof.go
Labels: size/XS, lgtm, approved

#1567 feat: support additional OIDC parameters
  pkg/apiserver/user/sso/service.go
  pkg/config/dynamic_config.go
  ui/packages/tidb-dashboard-client/src/client/api/models/config-ssocore-config.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/components/Form.SSO.tsx
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/client/models.ts
Labels: area/frontend, lgtm, approved, size/M

#1599 chore(sso): improve client secret security
  pkg/apiserver/user/sso/router.go
  pkg/config/dynamic_config_manager.go
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/components/Form.SSO.tsx
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/zh.yaml
Labels: area/frontend, lgtm, approved, size/M

#1601 chore(topsql): adjust TopSQL for clinic
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-lib/src/apps/Monitoring/components/Monitoring.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Metrics.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
  ui/packages/tidb-dashboard-lib/src/components/LimitTimeRange/index.tsx
  ui/packages/tidb-dashboard-lib/src/components/index.ts
Labels: area/frontend, lgtm, approved, size/L

#1602 chore(sso): support customize OIDC scopes
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/components/Form.SSO.tsx
Labels: area/frontend, lgtm, approved, size/S

#1603 chore(clinic): support redirect back after login for clinic
  ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
Labels: area/frontend, size/XS, lgtm, approved

#1605 chore(topsql): remove username for clinic
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
Labels: area/frontend, size/XS

#1600 profiling: Add the support for TiKV heap profiling
  pkg/apiserver/profiling/fetcher.go
  pkg/apiserver/profiling/jeprof.in
  pkg/apiserver/profiling/model.go
  pkg/apiserver/profiling/pprof.go
  pkg/apiserver/profiling/profile.go
  pkg/apiserver/profiling/router.go
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/Detail.tsx
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/pages/Detail.tsx
Labels: area/frontend, size/XXL, lgtm, approved

#1526 increase the upper limit of testing time
  scripts/_inc/run_services.sh
Labels: size/XS, lgtm, approved
