Repository pingcap/tidb-dashboard, pull requests merged in 2023-11, with the labels that each got.

#1516 fix cannot login when use ipv6 address
  cmd/tidb-dashboard/main.go
  pkg/apiserver/clusterinfo/statistics.go
  pkg/apiserver/configuration/service.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/logsearch/task.go
  pkg/apiserver/metrics/prom_resolve.go
  pkg/apiserver/profiling/fetcher.go
  pkg/pd/client.go
  pkg/tidb/client.go
  pkg/tidb/forwarder.go
  pkg/tiflash/client.go
  pkg/tikv/client.go
  util/client/tidbclient/sql_client.go
Labels: status/LGT1, lgtm, approved, size/M

#1608 tweak: explicitly set session max_execution_time to 600s
  pkg/tidb/client.go
Labels: size/XS, lgtm, approved

#1609 Release v2023.11.02.1
  pkg/apiserver/user/auth.go
  pkg/apiserver/user/rsa_utils.go
  pkg/apiserver/user/sqlauth/sqlauth.go
  release-version
  tests/integration/info/info_test.go
  tests/integration/user/user_test.go
  ui/packages/tidb-dashboard-client/src/client/api/models/user-get-login-info-response.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-op/package.json
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/signin/index.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/pnpm-lock.yaml
Labels: area/frontend, size/XXL

#1610 profiling: reuse convertDotToSVG to generate tikv heap profile svg
  pkg/apiserver/profiling/router.go
Labels: size/XS, lgtm, approved

#1611 Release v2023.11.08.1 [skip pd_pr]
  cmd/tidb-dashboard/main.go
  pkg/apiserver/clusterinfo/statistics.go
  pkg/apiserver/configuration/service.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/logsearch/task.go
  pkg/apiserver/metrics/prom_resolve.go
  pkg/apiserver/profiling/fetcher.go
  pkg/apiserver/profiling/jeprof.in
  pkg/apiserver/profiling/model.go
  pkg/apiserver/profiling/pprof.go
  pkg/apiserver/profiling/profile.go
  pkg/apiserver/profiling/router.go
  pkg/apiserver/statement/models.go
  pkg/apiserver/user/auth.go
  pkg/apiserver/user/rsa_utils.go
  pkg/apiserver/user/sqlauth/sqlauth.go
  pkg/apiserver/user/sso/router.go
  pkg/apiserver/user/sso/service.go
  pkg/config/dynamic_config.go
  pkg/config/dynamic_config_manager.go
  pkg/pd/client.go
  pkg/tidb/client.go
  pkg/tidb/forwarder.go
  pkg/tiflash/client.go
  pkg/tikv/client.go
  release-version
  scripts/_inc/run_services.sh
  tests/integration/info/info_test.go
  tests/integration/user/user_test.go
  ui/packages/tidb-dashboard-client/src/client/api/models/config-ssocore-config.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/user-get-login-info-response.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
  ui/packages/tidb-dashboard-for-op/package.json
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/signin/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/Detail.tsx
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/pages/Detail.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Monitoring/components/Monitoring.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Metrics.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetailTabBasic.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/tableColumns.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/components/Form.SSO.tsx
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/packages/tidb-dashboard-lib/src/components/LimitTimeRange/index.tsx
  ui/packages/tidb-dashboard-lib/src/components/index.ts
  ui/pnpm-lock.yaml
  util/client/tidbclient/sql_client.go
Labels: area/frontend, size/XXL

#1607 feat(conprof): support conprof on new o11y
  ui/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/ContinuousProfiling/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/ContinuousProfiling/index.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/utils/globalConfig.ts
  ui/packages/tidb-dashboard-for-op/src/apps/ContinuousProfiling/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/Detail.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/utils/distro.ts
Labels: area/frontend, size/L

#1612 *: add fips build support
  Makefile
  pkg/utils/version/fips.go
Labels: lgtm, approved, size/S

#1616 *: update gin to v1.9.1 for security reason
  go.mod
  go.sum
  scripts/go.mod
  scripts/go.sum
Labels: area/frontend, lgtm, approved, size/L

#1619 chore: fix goleak check
  util/testutil/testdefault/main.go
Labels: size/XS, lgtm, approved

#1617 fix: update axios to fix security issue
  ui/packages/clinic-client/package.json
  ui/packages/tidb-dashboard-client/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-clinic-op/package.json
  ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-dbaas/package.json
  ui/packages/tidb-dashboard-for-op/package.json
  ui/packages/tidb-dashboard-lib/package.json
  ui/pnpm-lock.yaml
Labels: area/frontend, size/M

#1620 Release 20231127
  go.mod
  go.sum
  release-version
  scripts/go.mod
  scripts/go.sum
  ui/packages/clinic-client/package.json
  ui/packages/tidb-dashboard-client/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-clinic-op/package.json
  ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-dbaas/package.json
  ui/packages/tidb-dashboard-for-op/package.json
  ui/packages/tidb-dashboard-lib/package.json
  ui/pnpm-lock.yaml
  util/testutil/testdefault/main.go
Labels: area/frontend, lgtm, approved, size/XL
