Repository pingcap/tidb-dashboard, pull requests merged in 2023-07, with the labels that each got.

#1555 chore(resource-manager): update tooltip content and style
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/components/EstimateCapacity.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/translations/zh.yaml
Labels: area/frontend, size/S

#1556 Release v2023.07.05.1 [skip pd_pr]
  release-version
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/components/EstimateCapacity.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/utils/openLink.ts
Labels: area/frontend, size/M

#1558 chore: fix prometheus typo
  ui/packages/tidb-dashboard-lib/src/apps/Monitoring/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Monitoring/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Overview/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Overview/translations/zh.yaml
Labels: area/frontend, size/XS, lgtm, approved

#1559 fix(manual-profiling): fix crash caused by undefined filed `raw_data_type`
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/pages/Detail.tsx
Labels: area/frontend, size/XS, lgtm, approved

#1562 tweak: allows custom names to pass tls verification
  cmd/tidb-dashboard/main.go
Labels: lgtm, approved, size/M

#1561 feat(execution-plan): refine execution plan
  pkg/apiserver/slowquery/model.go
  pkg/apiserver/slowquery/queries.go
  pkg/apiserver/statement/models.go
  pkg/apiserver/statement/service.go
  pkg/apiserver/utils/binary_plan.go
  ui/packages/tidb-dashboard-client/src/client/api/models/slowquery-model.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetail.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/index.tsx
  ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/sample-data/binary-plan.json
  ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/sample-data/detail-res.json
  ui/packages/tidb-dashboard-lib/src/components/index.ts
Labels: area/frontend, size/XXL, lgtm, approved

#1563 tweak: allows prom addr with http path
  pkg/apiserver/metrics/prom_resolve.go
  pkg/apiserver/metrics/prom_resolve_test.go
Labels: lgtm, approved, size/S

#1565 chore(binary-plan): truncate long operator info for execution plan
  ui/packages/tidb-dashboard-client/src/client/api/models/slowquery-model.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/index.tsx
Labels: area/frontend, lgtm, approved, size/S

#1564 fix: add endpoint verification in debugapi to avoid ssrf
  pkg/apiserver/debugapi/endpoint/errors.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/debugapi/endpoint/payload_test.go
  pkg/apiserver/debugapi/service.go
Labels: lgtm, approved, size/L
