Repository pingcap/tidb-dashboard, pull requests merged in 2023-06, with the labels that each got.

#1531 fix: make Resource Manager entry show correctly
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/main/Sider/index.tsx
Labels: area/frontend, size/XS, lgtm, approved

#1532 Release v2023.06.07.1 [skip pd_pr]
  OWNERS
  release-version
  ui/OWNERS
  ui/netlify.toml
  ui/packages/clinic-client/gulpfile.esm.js
  ui/packages/tidb-dashboard-client/gulpfile.esm.js
  ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
  ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/index.tsx
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/main/Sider/index.tsx
Labels: size/M

#1534 chore: hide system report for clinic cloud
  ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/layout/main/Sider/index.tsx
Labels: area/frontend, size/XS, lgtm, approved

#1543 Release v6.5.3 [skip pd_pr]
  release-version
Labels: size/XS, lgtm, approved

#1544 resource_manager: update resource manager cpu for instance
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/uilts/metricQueries.ts
Labels: area/frontend, size/XS, lgtm, approved

#1546 ci: fix `run_services.sh` for tiup
  scripts/_inc/run_services.sh
Labels: size/XS, lgtm, approved

#1548 resource_manager: fix burstable
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/components/EstimateCapacity.tsx
Labels: area/frontend, size/XS, lgtm, approved

#1549 chore: not use `root` as default login user name
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/signin/index.tsx
Labels: area/frontend, size/XS, lgtm, approved

#1550 chore: enlarge resource group column width to show long name
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/components/Configuration.tsx
Labels: area/frontend, size/XS, approved

#1551 Release v2023.06.28.1 [skip pd_pr]
  release-version
  scripts/_inc/run_services.sh
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/signin/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/components/Configuration.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/components/EstimateCapacity.tsx
Labels: area/frontend, lgtm, approved, size/S

#1552 chore: refine for clinic
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/utils/openLink.ts
Labels: area/frontend, lgtm, approved, size/M
