Repository pingcap/tidb-dashboard, pull requests merged in 2023-12, with the labels that each got.

#1621 feat(slow-query): show org and cluster info in clinic
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
Labels: area/frontend, size/M

#1623 *: add fips build support (#1612)
  Makefile
  pkg/utils/version/fips.go
Labels: size/S

#1624 profiling: Pass the TLS certificate to jeprof
  cmd/tidb-dashboard/main.go
  pkg/apiserver/profiling/fetcher.go
  pkg/apiserver/profiling/jeprof.in
  pkg/config/config.go
  pkg/tikv/client.go
Labels: size/L

#1614 profiling: use debug=1 for goroutine profile to avoid STW
  pkg/apiserver/profiling/pprof.go
Labels: size/XS

#1622 add ticdc topology in apiserver
  pkg/apiserver/apiserver.go
  pkg/apiserver/clusterinfo/host.go
  pkg/apiserver/clusterinfo/service.go
  pkg/apiserver/clusterinfo/statistics.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/model/common_models.go
  pkg/utils/topology/models.go
  pkg/utils/topology/ticdc.go
  util/client/ticdcclient/status_client.go
  util/topo/model.go
Labels: size/L

#1626 Release 20231218
  cmd/tidb-dashboard/main.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/clusterinfo/host.go
  pkg/apiserver/clusterinfo/service.go
  pkg/apiserver/clusterinfo/statistics.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/model/common_models.go
  pkg/apiserver/profiling/fetcher.go
  pkg/apiserver/profiling/jeprof.in
  pkg/apiserver/profiling/pprof.go
  pkg/config/config.go
  pkg/tikv/client.go
  pkg/utils/topology/models.go
  pkg/utils/topology/ticdc.go
  release-version
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  util/client/ticdcclient/status_client.go
  util/topo/model.go
Labels: area/frontend, lgtm, approved, size/XL

#1632 add more deploy info to ticdc
  pkg/utils/topology/ticdc.go
Labels: lgtm, approved, size/S

#1627 chore(build): update Makefile and CI to adjust release mode
  .github/workflows/manual-create-pd-pr.yaml
  .github/workflows/release-check.yaml
  .github/workflows/release.yaml
  .github/workflows/test-docker-image.yaml
  CONTRIBUTING.md
  Makefile
  scripts/create_release_tag.js
  ui/.env.development
  ui/packages/tidb-dashboard-for-op/builder.js
Labels: area/frontend, approved, size/L

#1629 feat: support TiProxy & TiCDC components in FE side
  ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/index.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/model-request-target-statistics.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/topology-ti-cdcinfo.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/topology-ti-proxy-info.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-op/src/apps/ClusterInfo/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/InstanceProfiling/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/metricsQueries.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Overview/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/SearchLogs/context.ts
  ui/packages/tidb-dashboard-for-op/src/utils/distro/strings_res.json
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/DiskTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/HostTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/InstanceTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/utils/combineTargetStats.ts
  ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Instances.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Overview/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SearchLogs/components/SearchHeader.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SearchLogs/context/index.ts
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/packages/tidb-dashboard-lib/src/components/InstanceSelect/ValueDisplay.tsx
  ui/packages/tidb-dashboard-lib/src/components/InstanceSelect/index.tsx
  ui/packages/tidb-dashboard-lib/src/utils/instanceTable.ts
  ui/packages/tidb-dashboard-lib/src/utils/useClientRequest.ts
Labels: area/frontend, size/XXL

#1628 *: add backend supports for tiproxy & ticdc
  pkg/apiserver/apiserver.go
  pkg/apiserver/clusterinfo/host.go
  pkg/apiserver/clusterinfo/hostinfo/hostinfo.go
  pkg/apiserver/clusterinfo/service.go
  pkg/apiserver/clusterinfo/statistics.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/debugapi/service.go
  pkg/apiserver/model/common_models.go
  pkg/apiserver/profiling/fetcher.go
  pkg/apiserver/profiling/profile.go
  pkg/ticdc/client.go
  pkg/ticdc/ticdc.go
  pkg/tiproxy/client.go
  pkg/tiproxy/tiproxy.go
  pkg/utils/topology/models.go
  pkg/utils/topology/tiproxy.go
  ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/index.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/model-request-target-statistics.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/topology-ti-cdcinfo.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/topology-ti-proxy-info.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/ClusterInfo/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/InstanceProfiling/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SearchLogs/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/ClusterInfo/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/InstanceProfiling/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/metricsQueries.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Overview/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/SearchLogs/context.ts
  ui/packages/tidb-dashboard-for-op/src/utils/distro/strings_res.json
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/DiskTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/HostTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/InstanceTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/utils/combineTargetStats.ts
  ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Instances.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Overview/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SearchLogs/components/SearchHeader.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SearchLogs/context/index.ts
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/packages/tidb-dashboard-lib/src/components/InstanceSelect/ValueDisplay.tsx
  ui/packages/tidb-dashboard-lib/src/components/InstanceSelect/index.tsx
  ui/packages/tidb-dashboard-lib/src/utils/instanceTable.ts
  ui/packages/tidb-dashboard-lib/src/utils/useClientRequest.ts
  util/client/tiproxyclient/status_client.go
  util/distro/distro.go
  util/topo/model.go
Labels: area/frontend, size/XXL, approved

#1634 fix: remove duplicated `v` in version showing in the banner
  ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/layout/main/Sider/Banner.tsx
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/main/Sider/Banner.tsx
Labels: area/frontend, size/S
