Repository pingcap/tidb-dashboard, pull requests merged in 2023-08, with the labels that each got.

#1570 Release v7.3.0 [skip pd_pr]
  release-version
Labels: size/XS, lgtm, approved

#1569 feat: allows ngm timeout to be configured
  cmd/tidb-dashboard/main.go
  pkg/apiserver/utils/ngm.go
  pkg/config/config.go
Labels: area/frontend, lgtm, approved, size/M

#1568 feat: fix and refine execution plan
  pkg/apiserver/slowquery/model.go
  pkg/apiserver/slowquery/queries.go
  pkg/apiserver/slowquery/service.go
  pkg/apiserver/statement/models.go
  pkg/apiserver/statement/service.go
  pkg/apiserver/utils/binary_plan.go
  ui/packages/tidb-dashboard-client/src/client/api/models/slowquery-model.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetail.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/BinaryPlanColsSelector.tsx
  ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/index.tsx
  ui/packages/tidb-dashboard-lib/src/components/PlanText/index.tsx
  ui/packages/tidb-dashboard-lib/src/components/TxtDownloadLink/index.module.less
  ui/packages/tidb-dashboard-lib/src/components/TxtDownloadLink/index.tsx
  ui/packages/tidb-dashboard-lib/src/components/index.ts
  ui/packages/tidb-dashboard-lib/src/utils/local-download.ts
Labels: area/frontend, size/XXL, lgtm, approved, affects-6.1, affects-7.1, affects-6.5

#1574 chore(binary-plan): show eye icon to hide column when hover
  ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/index.module.less
  ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/index.tsx
Labels: area/frontend, lgtm, approved, size/M

#1572 Release v2023.08.15.1 [skip pd_pr]
  cmd/tidb-dashboard/main.go
  pkg/apiserver/debugapi/endpoint/errors.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/debugapi/endpoint/payload_test.go
  pkg/apiserver/debugapi/service.go
  pkg/apiserver/metrics/prom_resolve.go
  pkg/apiserver/metrics/prom_resolve_test.go
  pkg/apiserver/statement/service.go
  pkg/apiserver/utils/ngm.go
  pkg/config/config.go
  release-version
  ui/packages/tidb-dashboard-lib/package.json
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/pages/Detail.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Monitoring/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Monitoring/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Overview/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Overview/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/components/charts/ScatterChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/components/charts/TimeSeriesChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Comparison/Comparison.module.less
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Comparison/Selections.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Comparison/charts/ComparisonCharts.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Comparison/charts/GroupBarChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Comparison/charts/ScatterCharts.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Comparison/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/ListV2/Analyzing.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/ListV2/ExpandChart/ExpandChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/ListV2/ExpandChart/Selections.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/ListV2/List.module.less
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/ListV2/Selections.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/ListV2/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/index.ts
  ui/pnpm-lock.yaml
Labels: area/frontend, size/XXL, lgtm, approved

#1575 bump: i18next
  ui/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/layout/main/Sider/Banner.tsx
  ui/packages/tidb-dashboard-for-clinic-op/package.json
  ui/packages/tidb-dashboard-for-dbaas/package.json
  ui/packages/tidb-dashboard-for-op/package.json
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/main/Sider/Banner.tsx
  ui/packages/tidb-dashboard-lib/package.json
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/ConProfSettingForm.tsx
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/apilist/ApiList.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/DetailTabTime.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetailTabTime.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SystemReport/components/ReportHistory.tsx
  ui/pnpm-lock.yaml
Labels: area/frontend, size/XXL, lgtm, approved

#1577 Yifan/release 7.1.1 [skip pd_pr]
  release-version
Labels: size/XS, lgtm, approved

#1578 Remove PNPM_INSTALL_TAGS=--offline
  dockerfiles/alpine316.Dockerfile
  dockerfiles/centos7.Dockerfile
Labels: size/XS, lgtm, approved

#1580 chore: upgrade node from 16 to 18, pnpm from 7 to 8
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  .github/workflows/upload-e2e-snapshots.yaml
  CONTRIBUTING.md
  ui/README.md
  ui/package.json
  ui/pnpm-lock.yaml
Labels: area/frontend, size/XXL, lgtm, approved

#1581 feat(conprof): show conprof download link for TiCDC
  pkg/apiserver/conprof/service.go
  ui/packages/tidb-dashboard-client/src/client/api/models/conprof-component-num.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/utils/distro/strings_res.json
  ui/packages/tidb-dashboard-for-op/src/utils/distro/strings_res.json
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/DiskTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/HostTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/packages/tidb-dashboard-lib/src/components/InstanceSelect/ValueDisplay.tsx
  ui/packages/tidb-dashboard-lib/src/utils/instanceTable.ts
  util/distro/distro.go
Labels: area/frontend, size/M

#1579 keyvisual: use scanRegions instead of fetch all regions
  pkg/keyvisual/input/api.go
Labels: lgtm, approved, size/M

#1582 feat(resource-control): show resource control entry for clinic
  ui/packages/tidb-dashboard-for-clinic-cloud/public/index.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/ResourceManager/context-impl.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/ResourceManager/index.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/ResourceManager/meta.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/layout/main/Sider/index.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/main.tsx
Labels: area/frontend, lgtm, approved, size/L

#1584 feat(debug-api): support pagination for ddl history
  pkg/apiserver/debugapi/apis.go
  pkg/apiserver/debugapi/endpoint/models.go
  ui/packages/tidb-dashboard-for-op/src/utils/distro/strings_res.json
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/apilist/ApiForm.tsx
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/translations/en.yaml
Labels: area/frontend, lgtm, approved, size/M

#1583 feat(security): encrypt login password
  pkg/apiserver/user/auth.go
  pkg/apiserver/user/rsa_utils.go
  pkg/apiserver/user/sqlauth/sqlauth.go
  ui/packages/tidb-dashboard-client/src/client/api/models/user-get-login-info-response.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-op/package.json
  ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/signin/index.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/pnpm-lock.yaml
Labels: area/frontend, size/XXL, lgtm, approved
