Repository pingcap/tidb-dashboard, pull requests merged in 2024-06, with the labels that each got.

#1686 ui: TopSQL can be configured to display the top n results
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
Labels: area/frontend, lgtm, approved, size/M, task

#1687 chore(top-slowquery): add more telemetry
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/telemetry.ts
Labels: area/frontend, approved, size/M, task, no-ct

#1689 chore(topsql): only show limit select for op
  ui/packages/tidb-dashboard-for-op/src/apps/TopSQL/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
Labels: area/frontend, size/M, task, no-ct

#1695 fix(slow-query): fix cannot show RU in slow query detail page
  pkg/apiserver/slowquery/queries.go
  pkg/apiserver/slowquery/service.go
  tests/integration/slowquery/mock_db_test.go
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
Labels: area/frontend, approved, size/M, task, no-ct
