Repository pingcap/tidb-dashboard, pull requests merged in 2024-03, with the labels that each got.

#1652 fix: fix debug paramters
  ui/packages/tidb-dashboard-for-op/.env.development
  util/rest/error_resp.go
Labels: area/frontend

#1654 feat(topsql): add action to search in sql statements
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/translations/zh.yaml
Labels: area/frontend, lgtm, approved, size/M

#1648 Add backend supports for tso and scheduling
  pkg/apiserver/apiserver.go
  pkg/apiserver/clusterinfo/host.go
  pkg/apiserver/clusterinfo/hostinfo/hostinfo.go
  pkg/apiserver/clusterinfo/service.go
  pkg/apiserver/clusterinfo/statistics.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/debugapi/service.go
  pkg/apiserver/model/common_models.go
  pkg/apiserver/profiling/fetcher.go
  pkg/apiserver/profiling/profile.go
  pkg/scheduling/client.go
  pkg/scheduling/scheduling.go
  pkg/tso/client.go
  pkg/tso/tso.go
  pkg/utils/topology/models.go
  pkg/utils/topology/scheduling.go
  pkg/utils/topology/tso.go
  ui/packages/clinic-client/src/client/api/api.ts
  ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
  ui/packages/tidb-dashboard-client/src/client/api/api/statement-api.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/index.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/model-request-target-statistics.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/topology-scheduling-info.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/topology-tsoinfo.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/ClusterInfo/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/InstanceProfiling/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SearchLogs/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/ClusterInfo/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/InstanceProfiling/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Overview/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/SearchLogs/context.ts
  ui/packages/tidb-dashboard-for-op/src/utils/distro/strings_res.json
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/DiskTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/HostTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/InstanceTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/utils/combineTargetStats.ts
  ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Instances.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Overview/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SearchLogs/components/SearchHeader.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SearchLogs/context/index.ts
  ui/packages/tidb-dashboard-lib/src/client/models.ts
  ui/packages/tidb-dashboard-lib/src/components/InstanceSelect/ValueDisplay.tsx
  ui/packages/tidb-dashboard-lib/src/components/InstanceSelect/index.tsx
  ui/packages/tidb-dashboard-lib/src/utils/instanceTable.ts
  util/client/schedulingclient/status_client.go
  util/client/tsoclient/status_client.go
  util/distro/distro.go
  util/topo/model.go
Labels: area/frontend, size/XXL, lgtm, approved

#1655 feat(tiproxy): support conprof and debug api for tiproxy
  pkg/apiserver/debugapi/apis.go
  pkg/apiserver/debugapi/endpoint/payload.go
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/DebugAPI/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/DebugAPI/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/apilist/ApiForm.tsx
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/apilist/ApiList.tsx
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/apilist/widgets/Host.tsx
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/translations/en.yaml
Labels: area/frontend, size/M

#1656 fix(debug-data): fix the wrong file ext for tiproxy config
  pkg/apiserver/debugapi/apis.go
  pkg/apiserver/debugapi/service.go
Labels: size/S

#1653 feat(top_slowquery): implement the ui
  .prettierrc
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/context-provider.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/index.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/meta.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/sample-data/slowqueries.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/main.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/utils/globalConfig.ts
  ui/packages/tidb-dashboard-lib/package.json
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/useSlowQueryTableController.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/CountChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.module.less
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/translations/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/helpers.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/url-state.ts
  ui/packages/tidb-dashboard-lib/src/apps/index.ts
  ui/pnpm-lock.yaml
Labels: area/frontend, size/XXL, lgtm, approved

#1657 chore(topsql): hide action in table for clinic
  ui/packages/clinic-client/src/client/api/api.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListTable.tsx
Labels: area/frontend, lgtm, approved, size/S

#1658 chore(top_slowquery): address feedback
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/CountChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
Labels: area/frontend, size/S

#1661 chore(top_slowuqery): address feedback
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/context-provider.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/CountChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.module.less
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/helpers.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/url-state.ts
Labels: area/frontend, lgtm, approved, size/L, task, no-ct

#1663 chore(top_slowquery): hide 7 days duration
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/helpers.ts
Labels: area/frontend, size/XS, lgtm, approved, task, no-ct

#1664 fix(cluster_info): fix error for hosts/disks/statistics page
  pkg/apiserver/clusterinfo/host.go
  pkg/apiserver/clusterinfo/statistics.go
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/Statistics.tsx
Labels: area/frontend, size/M, task, no-ct
