Repository pingcap/tidb-dashboard, pull requests merged in 2024-02, with the labels that each got.

#1646 feat(slow-query): support slow query search by resource group
  pkg/apiserver/resource_manager/service.go
  pkg/apiserver/slowquery/queries.go
  ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/slowquery-get-list-request.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Statement/context.ts
  ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Statement/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/useSlowQueryTableController.ts
  ui/packages/tidb-dashboard-lib/src/client/models.ts
Labels: area/frontend, lgtm, approved, size/XL

#1647 feat(statements): support statement search by resource group
  pkg/apiserver/statement/queries.go
  pkg/apiserver/statement/service.go
  ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-get-statements-request.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Statement/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Statement/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/useStatementTableController.ts
  ui/packages/tidb-dashboard-lib/src/client/models.ts
Labels: area/frontend, lgtm, approved, size/L

#1643 use topology for ticdc
  pkg/utils/topology/ticdc.go
Labels: size/XS, approved

#1645 Make KeyVisualizer disabled by default
  cmd/tidb-dashboard/main.go
  pkg/config/config.go
  pkg/config/dynamic_config_manager.go
Labels: lgtm, approved, size/M

#1649 fix: correctly display the disk mount points of tiflash
  pkg/apiserver/clusterinfo/hostinfo/cluster_config.go
Labels: lgtm, approved, size/M
