Repository pingcap/tidb-dashboard, pull requests merged in 2024-04, with the labels that each got.

#1665 feat(top_slowquery): support select time range on the chart
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/context-provider.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/CountChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/helpers.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/url-state.ts
Labels: area/frontend, lgtm, approved, size/L, task, no-ct

#1668 feat(slow_query): download db file for slow query
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/DownloadDBFileModal.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
Labels: area/frontend, lgtm, approved, size/L

#1670 chore(ci): cancel codecov upload
  .github/workflows/test.yaml
Labels: size/M

#1666 refactor(slow_query): move filter state to url, use react-query
  ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/components/SlowQueriesTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/detail-url-state.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/helpers.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/list-url-state.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
Labels: area/frontend, size/XXL, approved, task

#1672 fix(slow_query): fix download slowlog api, add range preview and timezone reminder
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/DownloadDBFileModal.tsx
Labels: area/frontend, lgtm, approved, size/M
