Repository pingcap/tidb-dashboard, pull requests merged in 2024-09, with the labels that each got.

#1736 fix build fail
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  ui/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/UserProfile/context.ts
Labels: area/frontend, size/S

#1737 fix: revert limit pnpm version
  .github/workflows/test.yaml
  ui/package.json
Labels: area/frontend, size/M

#1732 topsql: add ui for aggregating by table or db
  pkg/apiserver/topsql/service.go
  ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/index.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/topsql-summary-by-item.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/topsql-summary-response.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSQL/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/TopSQL/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/utils/specialRecord.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
Labels: area/frontend, size/XXL, lgtm, approved, story

#1738 clusterinfo: fix ssrf on /topology/alertmanager/{address}/count
  pkg/apiserver/clusterinfo/service.go
Labels: lgtm, approved, size/S, task, no-ct
