Repository pingcap/tidb-dashboard, pull requests merged in 2024-05, with the labels that each got.

#1667 feat(top_slowquery): support multiple db and statement type filter
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/context-provider.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/list-url-state.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.module.less
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/helpers.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/url-state.ts
Labels: area/frontend, size/L, task

#1674 chore: hide some features for clinic and update distro res
  ui/packages/tidb-dashboard-for-clinic-cloud/public/index.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/main.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/diagnoseReportApp/index.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/utils/distro/strings_res.json
  ui/packages/tidb-dashboard-lib/src/apps/Overview/index.tsx
Labels: area/frontend, lgtm, approved, size/S, task, no-ct

#1675 feat: support download table to csv for top sql, slow query
  ui/packages/tidb-dashboard-lib/package.json
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListDetail/ListDetailTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/CountChart.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
  ui/pnpm-lock.yaml
Labels: area/frontend, lgtm, approved, size/L, task, no-ct

#1676 chore(telemetry): add telemetry for top slow query
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/telemetry.ts
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/telemetry.ts
Labels: area/frontend, lgtm, approved, size/M, task, no-ct

#1680 monitoring: fix the tps metric
  ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/metricsQueries.ts
Labels: area/frontend, size/XS, approved, task, no-ct

#1681 monitoring: fix tps for clinic
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Monitoring/metricsQueries.ts
  ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/metricsQueries.ts
Labels: area/frontend, size/XS, approved, task, no-ct
