Repository pingcap/tidb-dashboard, pull requests merged in 2024-01, with the labels that each got.

#1635 Update release-version
  release-version
Labels: size/XS

#1636 feat(slow-query): support slow query search by digest
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/InstanceTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Instances.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/components/Filter/InstanceSelect.tsx
Labels: area/frontend, size/M

#1638 chore: remove un-used code
  ui/.prettierignore
  ui/README.md
  ui/package.json
  ui/packages/tidb-dashboard-for-clinic-cloud/.env.development
  ui/packages/tidb-dashboard-for-clinic-cloud/public/o11y.html
  ui/packages/tidb-dashboard-for-dbaas/.env.development
  ui/packages/tidb-dashboard-for-dbaas/.env.production
  ui/packages/tidb-dashboard-for-dbaas/README.md
  ui/packages/tidb-dashboard-for-dbaas/builder.js
  ui/packages/tidb-dashboard-for-dbaas/gulpfile.esm.js
  ui/packages/tidb-dashboard-for-dbaas/package.json
  ui/packages/tidb-dashboard-for-dbaas/process-shim.js
  ui/packages/tidb-dashboard-for-dbaas/public/favicon.ico
  ui/packages/tidb-dashboard-for-dbaas/public/index.html
  ui/packages/tidb-dashboard-for-dbaas/public/test-cdn/index.html
  ui/packages/tidb-dashboard-for-dbaas/public/test-iframe/child.html
  ui/packages/tidb-dashboard-for-dbaas/public/test-iframe/external-link.svg
  ui/packages/tidb-dashboard-for-dbaas/public/test-iframe/maximize-2.svg
  ui/packages/tidb-dashboard-for-dbaas/public/test-iframe/maximize.svg
  ui/packages/tidb-dashboard-for-dbaas/public/test-iframe/minimize-2.svg
  ui/packages/tidb-dashboard-for-dbaas/public/test-iframe/minimize.svg
  ui/packages/tidb-dashboard-for-dbaas/public/test-iframe/parent.html
  ui/packages/tidb-dashboard-for-dbaas/src/App.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/apps/KeyViz/context.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/KeyViz/index.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/apps/Monitoring/context.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/Monitoring/index.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/apps/Monitoring/metricsQueries.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/SQLAdvisor/context.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/SQLAdvisor/index.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/apps/SQLAdvisor/meta.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/SlowQuery/context.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/SlowQuery/index.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/apps/Statement/context.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/Statement/index.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/apps/TopSQL/context.ts
  ui/packages/tidb-dashboard-for-dbaas/src/apps/TopSQL/index.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/client/index.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/client/translations/en.yaml
  ui/packages/tidb-dashboard-for-dbaas/src/client/translations/index.ts
  ui/packages/tidb-dashboard-for-dbaas/src/client/translations/zh.yaml
  ui/packages/tidb-dashboard-for-dbaas/src/index.tsx
  ui/packages/tidb-dashboard-for-dbaas/src/react-app-env.d.ts
  ui/packages/tidb-dashboard-for-dbaas/src/styles/override.less
  ui/packages/tidb-dashboard-for-dbaas/src/styles/style.less
  ui/packages/tidb-dashboard-for-dbaas/src/utils/global-config.ts
  ui/packages/tidb-dashboard-for-dbaas/src/utils/store.ts
  ui/packages/tidb-dashboard-for-dbaas/tsconfig.json
  ui/pnpm-lock.yaml
Labels: area/frontend, size/XXL, lgtm, approved

#1639 statement,slowquery: add request unit part in list
  pkg/apiserver/slowquery/model.go
  pkg/apiserver/slowquery/statement_gen.go
  pkg/apiserver/statement/models.go
  tests/schema/test.CLUSTER_SLOW_QUERY-schema.sql
  ui/packages/tidb-dashboard-client/src/client/api/models/slowquery-model.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/tableColumns.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/tableColumns.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
Labels: area/frontend, lgtm, approved, size/L

#1640 statement,slowquery: add request unit part in list (#1639)
  pkg/apiserver/slowquery/model.go
  pkg/apiserver/slowquery/statement_gen.go
  pkg/apiserver/statement/models.go
  tests/schema/test.CLUSTER_SLOW_QUERY-schema.sql
  ui/packages/tidb-dashboard-client/src/client/api/models/slowquery-model.ts
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/tableColumns.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/tableColumns.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
Labels: area/frontend, lgtm, approved, size/L

#1642 statement,slowquery: add request unit part in the detail page
  pkg/apiserver/statement/models.go
  ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/DetailTabBasic.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/DetailTabTime.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetailTabBasic.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetailTabTime.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/tableColumns.tsx
  ui/packages/tidb-dashboard-lib/src/client/models.ts
Labels: area/frontend, lgtm, approved, size/M
