Repository pingcap/tidb-dashboard, pull requests merged in 2024-07, with the labels that each got.

#1696 feat(keyviz): support config, hide setting for clinic
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/KeyViz/context.ts
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/KeyViz/index.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/utils/globalConfig.ts
  ui/packages/tidb-dashboard-lib/src/apps/KeyViz/components/KeyViz.tsx
  ui/packages/tidb-dashboard-lib/src/apps/KeyViz/components/KeyVizToolbar.tsx
  ui/packages/tidb-dashboard-lib/src/apps/KeyViz/context/index.ts
Labels: area/frontend, size/L

#1697 chore(statements): set statement config for clinic
  ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
Labels: area/frontend, size/XS

#1699 fix: fix calendar algorithm
  ui/packages/tidb-dashboard-lib/src/components/DateTime/calendarPlugin.ts
Labels: area/frontend, lgtm, approved, size/M, task, no-ct

#1705 chore: support x-env header
  ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
  ui/packages/tidb-dashboard-for-clinic-cloud/src/utils/globalConfig.ts
Labels: area/frontend, size/XS

#1700 feat: support multi batches for keyviz schema data
  pkg/keyvisual/decorator/tidb_requests.go
  pkg/tidb/model/model.go
Labels: lgtm, approved, size/L, task, no-ct
