Repository pingcap/tidb-dashboard, pull requests merged in 2024-08, with the labels that each got.

#1704 dashboard/api/host/all: add ticdc instance information to host/all api
  pkg/apiserver/clusterinfo/hostinfo/cluster_config.go
Labels: size/XS, lgtm, approved

#1707 update etcd to 3.5.15
  cmd/tidb-dashboard/main.go
  go.mod
  go.sum
  pkg/apiserver/clusterinfo/service.go
  pkg/apiserver/configuration/service.go
  pkg/apiserver/conprof/service.go
  pkg/apiserver/debugapi/endpoint/payload.go
  pkg/apiserver/debugapi/service.go
  pkg/apiserver/info/info.go
  pkg/apiserver/logsearch/task.go
  pkg/apiserver/metrics/service.go
  pkg/apiserver/profiling/service.go
  pkg/apiserver/utils/ngm.go
  pkg/config/config.go
  pkg/config/dynamic_config_manager.go
  pkg/keyvisual/decorator/tidb.go
  pkg/keyvisual/service.go
  pkg/pd/etcd.go
  pkg/tidb/client.go
  pkg/tidb/forwarder.go
  pkg/tikv/client.go
  pkg/utils/topology/monitor.go
  pkg/utils/topology/ticdc.go
  pkg/utils/topology/tidb.go
  pkg/utils/topology/tiproxy.go
  pkg/utils/topology/topology.go
  scripts/go.mod
  scripts/go.sum
  util/client/pdclient/etcd_client.go
  util/topo/pdtopo/monitor.go
  util/topo/pdtopo/provider_pd.go
  util/topo/pdtopo/std_comp.go
  util/topo/pdtopo/tidb.go
Labels: lgtm, approved, size/XL

#1713 dashboard/api/host/all: add ticdc instance information to host/all api
  pkg/apiserver/clusterinfo/hostinfo/cluster_config.go
Labels: size/XS

#1714 dashboard/api/host/all: add ticdc instance information to host/all api
  pkg/apiserver/clusterinfo/hostinfo/cluster_config.go
Labels: size/XS

#1717 *: add share code revoke api; add a config to allow disabling custom prom addr
  cmd/tidb-dashboard/main.go
  pkg/apiserver/metrics/router.go
  pkg/apiserver/metrics/service.go
  pkg/apiserver/user/code/router.go
  pkg/apiserver/user/code/service.go
  pkg/config/config.go
Labels: lgtm, approved, size/M, task, no-ct

#1720 chore: refine `make tag` script
  scripts/create_release_tag.js
Labels: size/M

#1721 chore: refine `make tag` script
  scripts/create_release_tag.js
Labels: size/XS

#1723 chore: fix typo
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
Labels: area/frontend, size/XS

#1724 chore: refine make tag
  scripts/create_release_tag.js
Labels: size/M

#1719 [cherry-pick] [release6.5] [#1717] *: add share code revoke api; add a config to allow disabling custom …
  cmd/tidb-dashboard/main.go
  pkg/apiserver/metrics/router.go
  pkg/apiserver/metrics/service.go
  pkg/apiserver/user/code/router.go
  pkg/apiserver/user/code/service.go
  pkg/config/config.go
Labels: lgtm, approved, size/M

#1726 chore(statement_slowquery): ignore resource manager api error
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/useSlowQueryTableController.ts
  ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/useStatementTableController.ts
Labels: area/frontend, size/XS

#1718 Support heap profiling for TiFlash
  pkg/apiserver/profiling/fetcher.go
  pkg/apiserver/profiling/pprof.go
  pkg/apiserver/profiling/profile.go
  pkg/tiflash/client.go
  ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/Detail.tsx
Labels: area/frontend, lgtm, approved, size/M, task, no-ct

#1728 feat(revoke-share-code): support revoke shared login code
  ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
  ui/packages/tidb-dashboard-client/swagger/spec.json
  ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/UserProfile/context.ts
  ui/packages/tidb-dashboard-for-op/src/apps/UserProfile/context.ts
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/components/Form.Session.tsx
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/context/index.ts
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/zh.yaml
Labels: area/frontend, size/L

#1730 chore: fix `make tag` and refine ci workflow
  .github/workflows/manual-create-pd-pr.yaml
  scripts/create_release_tag.js
Labels: size/S
