Repository pingcap/tidb-dashboard, pull requests merged in 2025-04, with the labels that each got.

#1780 ci: fix docker image build job
  .github/workflows/build.yaml
  .github/workflows/manual-create-pd-pr.yaml
  .github/workflows/release.yaml
  .github/workflows/test-docker-image.yaml
  .github/workflows/test.yaml
  .github/workflows/upload-e2e-snapshots.yaml
  dockerfiles/alpine316.Dockerfile
  dockerfiles/centos7.Dockerfile
Labels: lgtm, approved, size/L

#1776 fix call rest.NewErrorResponse with a nil value error
  pkg/apiserver/configuration/service.go
Labels: size/XS, lgtm, approved

#1786 chore(session): refine share code
  pkg/apiserver/user/code/router.go
  pkg/apiserver/user/code/service.go
  ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/apilist/ApiForm.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Diagnose/components/DiagnosisTable.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Diagnose/pages/DiagnoseGenerator.tsx
  ui/packages/tidb-dashboard-lib/src/apps/InstanceProfiling/pages/List.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SystemReport/pages/ReportGenerator.tsx
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/components/Form.Session.tsx
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/en.yaml
  ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/zh.yaml
Labels: area/frontend, size/L

#1788 fix(diagnosis): truncate long sql in frontend side to avoid page hang
  ui/packages/tidb-dashboard-lib/src/apps/Deadlock/pages/Detail.tsx
  ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetail.tsx
  ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/index.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListDetail/ListDetailContent.tsx
  ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListTable.tsx
  ui/packages/tidb-dashboard-lib/src/components/HighlightSQL/index.tsx
  ui/packages/tidb-dashboard-lib/src/utils/tableColumnFactory.tsx
Labels: area/frontend, size/L
